### ISSUE TITLE
can not change to no-static?

### ISSUE THREAD

**Issue by yanhuibin315** [IBM/blockchain-application-using-fabric-java-sdk#14]
I change queryfunction in a non-static function. but it will be wrong for NullPoint?

**Comment by balajikadambi** [comment]
@yanhuibin315 could you provide me more details on the issue. It can be made into a non-static function with necessary code changes.

**Comment by yanhuibin315** [comment]
the all details:
[root@localhost network_resources]# java -cp culebao.jar main.java.org.app.chaincode.invocation.QueryChaincode
Dec 10, 2018 9:15:39 PM main.java.org.app.util.Util deleteDirectory
INFO: Deleting - admin.ser
Dec 10, 2018 9:15:39 PM main.java.org.app.util.Util deleteDirectory
INFO: Deleting - org1
Dec 10, 2018 9:15:39 PM main.java.org.app.util.Util deleteDirectory
INFO: Deleting - users
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Dec 10, 2018 9:15:47 PM main.java.org.app.client.CAClient enrollAdminUser
INFO: CA -http://localhost:7054 Enrolled Admin.
org.hyperledger.fabric.sdk.exception.TransactionException: sendDeliver time exceeded for orderer
	at org.hyperledger.fabric.sdk.OrdererClient.sendDeliver(OrdererClient.java:274)
	at org.hyperledger.fabric.sdk.Orderer.sendDeliver(Orderer.java:165)
	at org.hyperledger.fabric.sdk.Channel.getLatestBlock(Channel.java:1074)
	at org.hyperledger.fabric.sdk.Channel.getConfigurationBlock(Channel.java:898)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:826)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:526)
	at main.java.org.app.chaincode.invocation.QueryChaincode.selectRuleHistory(QueryChaincode.java:307)
	at main.java.org.app.chaincode.invocation.QueryChaincode.main(QueryChaincode.java:65)

**Comment by balajikadambi** [comment]
@yanhuibin315 try increasing the proposal wait time to see if it resolves the issue.
request.setProposalWaitTime(1000);

**Comment by yanhuibin315** [comment]
Sorry, I tried to increase the prososal wait time to 100000000, but I got the same wrong message like that ::
[root@localhost network_resources]# java -cp culebao.jar main.java.org.app.chaincode.invocation.QueryChaincode
Dec 11, 2018 2:53:44 PM main.java.org.app.util.Util deleteDirectory
INFO: Deleting - users
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Dec 11, 2018 2:53:45 PM main.java.org.app.client.CAClient enrollAdminUser
INFO: CA -http://localhost:7054 Enrolled Admin.
org.hyperledger.fabric.sdk.exception.TransactionException: Bad newest block expected status 200  got  404, Channel mychannel
	at org.hyperledger.fabric.sdk.Channel.getLatestBlock(Channel.java:1085)
	at org.hyperledger.fabric.sdk.Channel.getConfigurationBlock(Channel.java:898)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:826)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:526)
	at main.java.org.app.chaincode.invocation.QueryChaincode.selectRuleHistory(QueryChaincode.java:307)
	at main.java.org.app.chaincode.invocation.QueryChaincode.main(QueryChaincode.java:65)

**Comment by yanhuibin315** [comment]
But if I make the function to static . That would be ok

**Comment by yanhuibin315** [comment]
WOWWW ! I miss the step to createchannel , and now I process the function to non-static. Thank you ~~

**Comment by maheshwarishikha** [comment]
Closing the issue, as it worked for you. Thanks.
