### ISSUE TITLE
CreateChannel Error!

### ISSUE THREAD

**Issue by yanhuibin315** [IBM/blockchain-application-using-fabric-java-sdk#17]
Hello,
I tried to make fabric-network in five server, one order, four peer, and I change the config and docker-compose.yml files , when I use jar to CreateChannel on one peer, I get ERROR MESSAGE like that :
org.hyperledger.fabric.sdk.exception.TransactionException: Send transactions failed. Reason:  timeout
        at org.hyperledger.fabric.sdk.OrdererClient.sendTransaction(OrdererClient.java:163)
        at org.hyperledger.fabric.sdk.Orderer.sendTransaction(Orderer.java:133)
        at org.hyperledger.fabric.sdk.Channel.<init>(Channel.java:222)
        at org.hyperledger.fabric.sdk.Channel.createNewInstance(Channel.java:1121)
        at org.hyperledger.fabric.sdk.HFClient.newChannel(HFClient.java:135)
        at main.java.org.app.network.CreateChannel.main(CreateChannel.java:76)

**Comment by yanhuibin315** [comment]
I got it that I could not close the firewall . thank you

**Comment by rituusjain** [comment]
I'm getting the same error, can someone post the fix please. Thanks!
