### ISSUE TITLE
Proposal response is invalid error when I invoke chaincode

### ISSUE THREAD

**Issue by heyxingtang** [IBM/blockchain-application-using-fabric-java-sdk#42]
when i execute `java -cp blockchain-client.jar org.example.chaincode.invocation.InvokeChaincode`, then
`root@fabric-VirtualBox:~/go/src/IBM/blockchain-application-using-fabric-java-sdk/network_resources# java -cp blockchain-client.jar org.example.chaincode.invocation.InvokeChaincode
Oct 03, 2019 9:38:44 PM org.example.util.Util deleteDirectory
INFO: Deleting - admin.ser
Oct 03, 2019 9:38:45 PM org.example.util.Util deleteDirectory
INFO: Deleting - user1570109909538.ser
Oct 03, 2019 9:38:45 PM org.example.util.Util deleteDirectory
INFO: Deleting - org1
Oct 03, 2019 9:38:45 PM org.example.util.Util deleteDirectory
INFO: Deleting - users
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 03, 2019 9:38:47 PM org.example.client.CAClient enrollAdminUser
INFO: CA -http://localhost:7054 Enrolled Admin.
Oct 03, 2019 9:38:50 PM org.example.client.ChannelClient sendTransactionProposal
INFO: Sending transaction proposal on channel mychannel
org.hyperledger.fabric.sdk.exception.InvalidArgumentException: Proposal response is invalid.
	at org.hyperledger.fabric.sdk.ProposalResponse.getChaincodeActionResponsePayload(ProposalResponse.java:272)
	at org.example.client.ChannelClient.sendTransactionProposal(ChannelClient.java:121)
	at org.example.chaincode.invocation.InvokeChaincode.main(InvokeChaincode.java:88)`

InvokeChaincode.java line 51 Util.cleanUp() empty the network_resources/users/

**Comment by maheshwarishikha** [comment]
@heyxingtang , did u make any changes in code? which version of fabric you are using?

**Comment by heyxingtang** [comment]
The hyperledger-fabric version is 1.4.1 and without changing the source code

**Comment by heyxingtang** [comment]
`[root@VM_0_39_centos network_resources]# java -cp blockchain-client.jar org.example.chaincode.invocation.InvokeChaincode
十月 05, 2019 9:53:33 上午 org.example.util.Util deleteDirectory
信息: Deleting - admin.ser
十月 05, 2019 9:53:33 上午 org.example.util.Util deleteDirectory
信息: Deleting - user1570240399744.ser
十月 05, 2019 9:53:33 上午 org.example.util.Util deleteDirectory
信息: Deleting - org1
十月 05, 2019 9:53:33 上午 org.example.util.Util deleteDirectory
信息: Deleting - users
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
十月 05, 2019 9:53:35 上午 org.example.client.CAClient enrollAdminUser
信息: CA -http://localhost:7054 Enrolled Admin.
十月 05, 2019 9:53:38 上午 org.example.client.ChannelClient sendTransactionProposal
信息: Sending transaction proposal on channel mychannel
org.hyperledger.fabric.sdk.exception.InvalidArgumentException: Proposal response is invalid.
	at org.hyperledger.fabric.sdk.ProposalResponse.getChaincodeActionResponsePayload(ProposalResponse.java:272)
	at org.example.client.ChannelClient.sendTransactionProposal(ChannelClient.java:121)
	at org.example.chaincode.invocation.InvokeChaincode.main(InvokeChaincode.java:88)
[root@VM_0_39_centos network_resources]# git status
# 位于分支 master
# 尚未暂存以备提交的变更：
#   （使用 "git add <file>..." 更新要提交的内容）
#   （使用 "git checkout -- <file>..." 丢弃工作区的改动）
#
#	修改：      ../network/build.sh
#	修改：      ../network/stop.sh
#	修改：      ../network/teardown.sh
#	修改：      crypto-config/peerOrganizations/org1.example.com/ca/fabric-ca-server.db
#	修改：      crypto-config/peerOrganizations/org2.example.com/ca/fabric-ca-server.db
#
# 未跟踪的文件:
#   （使用 "git add <file>..." 以包含要提交的内容）
#
#	../java/target/
#	blockchain-client.jar
#	crypto-config/peerOrganizations/org1.example.com/ca/IssuerPublicKey
#	crypto-config/peerOrganizations/org1.example.com/ca/IssuerRevocationPublicKey
#	crypto-config/peerOrganizations/org1.example.com/ca/msp/keystore/IssuerRevocationPrivateKey
#	crypto-config/peerOrganizations/org1.example.com/ca/msp/keystore/IssuerSecretKey
#	crypto-config/peerOrganizations/org2.example.com/ca/IssuerPublicKey
#	crypto-config/peerOrganizations/org2.example.com/ca/IssuerRevocationPublicKey
#	crypto-config/peerOrganizations/org2.example.com/ca/msp/keystore/IssuerRevocationPrivateKey
#	crypto-config/peerOrganizations/org2.example.com/ca/msp/keystore/IssuerSecretKey
#	users/
修改尚未加入提交（使用 "git add" 和/或 "git commit -a"）`

and the fabric verion
`[root@VM_0_39_centos scripts]# cd ..
[root@VM_0_39_centos fabric]# git branch -v
* （分离自 v1.4.1） 87074a7 [FAB-14966] Release fabric v1.4.1
  release-1.4       715c6ec [FAB-15261] Fix cc2cc discovery query bug
[root@VM_0_39_centos fabric]# pwd
/root/go/src/github.com/hyperledger/fabric`

**Comment by alecjonesnuyad05** [comment]
@heyxingtang Would like to ask if you able to resolve this issue on your end? Because I get the same error.
