### ISSUE TITLE
Cannot create channel

### ISSUE THREAD

**Issue by mesbahiayoub** [IBM/blockchain-application-using-fabric-java-sdk#44]
Hello,
I tried to creating the channel as follow `java -cp blockchain-client.jar org.example.network.CreateChannel`, but i keep getting this error :

`log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
oct. 17, 2019 12:38:37 AM org.example.util.Util deleteDirectory
INFOS: Deleting - users
org.hyperledger.fabric.sdk.exception.TransactionException: Channel mychannel, send transaction failed on orderer OrdererClient{id: 4, channel: mychannel, name: orderer.example.com, url: grpc://localhost:7050}. Reason: UNAVAILABLE: io exception
        at org.hyperledger.fabric.sdk.OrdererClient.sendTransaction(OrdererClient.java:236)
        at org.hyperledger.fabric.sdk.Orderer.sendTransaction(Orderer.java:161)
        at org.hyperledger.fabric.sdk.Channel.sendUpdateChannel(Channel.java:531)
        at org.hyperledger.fabric.sdk.Channel.<init>(Channel.java:247)
        at org.hyperledger.fabric.sdk.Channel.createNewInstance(Channel.java:340)
        at org.hyperledger.fabric.sdk.HFClient.newChannel(HFClient.java:222)
        at org.example.network.CreateChannel.main(CreateChannel.java:76)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:7050
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused: no further information
`
thanks for your help,

**Comment by Akilavasanthakumar93** [comment]
Am also facing same issue..Any solution for this..

**Comment by Akilavasanthakumar93** [comment]
> Am also facing same issue..Any solution for this..

issue resolved. Problem with docker images.

**Comment by mesbahiayoub** [comment]
@Akilavasanthakumar93  can please tell me what's the problem with docker image and how did you solve it.
Thanks a lot.

**Comment by Akilavasanthakumar93** [comment]
Orgs are refering with old images..I pulled new images..

**Comment by Varsh18** [comment]
I am also facing this issue .... Please help me to solve this out


java -cp blockchain-client.jar org.example.network.CreateChannel
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Nov 04, 2019 7:46:31 PM org.example.util.Util deleteDirectory
INFO: Deleting - users
org.hyperledger.fabric.sdk.exception.TransactionException: Channel mychannel, send transaction failed on orderer OrdererClient{id: 4, channel: mychannel, name: orderer.example.com, url: grpc://localhost:7050}. Reason: UNAVAILABLE: io exception
        at org.hyperledger.fabric.sdk.OrdererClient.sendTransaction(OrdererClient.java:236)
        at org.hyperledger.fabric.sdk.Orderer.sendTransaction(Orderer.java:161)
        at org.hyperledger.fabric.sdk.Channel.sendUpdateChannel(Channel.java:531)
        at org.hyperledger.fabric.sdk.Channel.<init>(Channel.java:247)
        at org.hyperledger.fabric.sdk.Channel.createNewInstance(Channel.java:340)
        at org.hyperledger.fabric.sdk.HFClient.newChannel(HFClient.java:222)
        at org.example.network.CreateChannel.main(CreateChannel.java:76)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:7050
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused: no further information
        ... 11 more

**Comment by mesbahiayoub** [comment]
@Akilavasanthakumar93 i tried pulling new image (as follow) but it didn't work : 

> $ docker pull hyperledger/fabric-ca
Using default tag: latest
latest: Pulling from hyperledger/fabric-ca
34667c7e4631: Already exists
d18d76a881a4: Already exists
119c7358fbfc: Already exists
2aaf13f3eff0: Already exists
3f89de4cf84b: Already exists
24194f819972: Already exists
414a8f56afc4: Pulling fs layer
d5aeaa3d2858: Pulling fs layer
248e89bdef30: Pulling fs layer
8feaa797dee8: Pulling fs layer
93b10fe11896: Pulling fs layer
8feaa797dee8: Waiting
93b10fe11896: Waiting
414a8f56afc4: Verifying Checksum
414a8f56afc4: Download complete
414a8f56afc4: Pull complete
d5aeaa3d2858: Verifying Checksum
d5aeaa3d2858: Download complete
d5aeaa3d2858: Pull complete
93b10fe11896: Verifying Checksum
93b10fe11896: Download complete
248e89bdef30: Verifying Checksum
248e89bdef30: Download complete
248e89bdef30: Pull complete
8feaa797dee8: Verifying Checksum
8feaa797dee8: Download complete
8feaa797dee8: Pull complete
93b10fe11896: Pull complete
Digest: sha256:82a7f653ed0de520bf3ee565a07a76aac8b91ed80869b33dddfec39652c9d183
Status: Downloaded newer image for hyperledger/fabric-ca:latest
docker.io/hyperledger/fabric-ca:latest

> 


I keep getting the same error :

**Comment by Akilavasanthakumar93** [comment]
@mesbahiayoub  
Before you start your network check local docker image version and docker-compose.yml  are contains same image version.

~/blockchain-application-using-fabric-java-sdk/network$ ./build.sh 

Stopping the previous network (if any)
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing peer1.org1.example.com ... done
Removing peer1.org2.example.com ... done
Removing ca_peerOrg2            ... done
Removing ca_peerOrg1            ... done
Removing orderer.example.com    ... done
Removing network network_custom

Setting up the Hyperledger Fabric 1.1 network
Creating network "network_custom" with the default driver
Creating ca_peerOrg1         ... done
Creating orderer.example.com ... done
Creating ca_peerOrg2         ... done
Creating peer1.org2.example.com ... done
Creating peer0.org1.example.com ... done
Creating peer1.org1.example.com ... done
Creating peer0.org2.example.com ... done

Network setup completed!!

~/blockchain-application-using-fabric-java-sdk/network_resources$ java -cp blockchain-client.jar org.example.network.CreateChannel 
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Nov 09, 2019 9:41:06 PM org.example.util.Util deleteDirectory
INFO: Deleting - users
Nov 09, 2019 9:41:12 PM org.example.network.CreateChannel main
INFO: Channel created mychannel
Nov 09, 2019 9:41:12 PM org.example.network.CreateChannel main
INFO: peer0.org2.example.com at grpc://localhost:8051
Nov 09, 2019 9:41:12 PM org.example.network.CreateChannel main
INFO: peer1.org1.example.com at grpc://localhost:7056
Nov 09, 2019 9:41:12 PM org.example.network.CreateChannel main
INFO: peer1.org2.example.com at grpc://localhost:8056
Nov 09, 2019 9:41:12 PM org.example.network.CreateChannel main
INFO: peer0.org1.example.com at grpc://localhost:7051
